gesdinet_jwt_refresh_token:
    ttl: 2592000 # 30 days in seconds
    user_provider: app_user_provider
    refresh_token_class: App\Entity\RefreshToken
    firewall: login
    token_parameter_name: refresh_token
    manager_type: orm


